server:
  port: 8083

spring:
  application:
    name: micro-authorization
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 193.168.1.201:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
